<a href="https://colab.research.google.com/github/kjeyaram-orcl/DataScience/blob/main/Numpy_DataDistribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#Create 1-D array containing 20 values, where each value has to be 2, 4, 6 or 8
from numpy import random

x = random.choice([2, 4, 6, 8], p=[0.1, 0.3, 0.4, 0.2], size=(20))

print(x)

[4 6 8 4 8 4 4 4 4 6 2 6 4 6 4 4 6 6 8 6]


In [9]:
#Create 3-D array containing 20 values, where each value has to be 2, 4, 6 or 8

from numpy import random

x = random.choice([2, 4, 6, 8], p=[0.1, 0.3, 0.4, 0.2], size=(2,2,5))

print(x)

[[[6 6 6 6 4]
  [4 8 6 6 4]]

 [[8 4 2 4 4]
  [8 4 6 6 6]]]
