<a href="https://colab.research.google.com/github/kjeyaram-orcl/DataScience/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#create 3×3 Matrix and make it as 3×4 matrix

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(a)
a_new=np.resize(a,(3,4)) # resize returns new array filled with repeated copies of a
print(a_new)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]


In [ ]:
import numpy as np

#8x8 matrix pattern using numpy with 1 for black and 0 for white

a=np.full((4, 8), [0,1,0,1,0,1,0,1])
print("Create 4x8 filled with 0 & 1")
print(a)
b=np.full((4, 8), [1,0,1,0,1,0,1,0])
print("Create 4x8 filled with 1 & 0")
print(b)
c=np.concatenate((a, b),axis=1)
print("concatenate a & b along row axis")
print (c)
d=c.reshape(8,8)
print("Reshape without changing data")
print(d)

Create 4x8 filled with 0 & 1
[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]
Create 4x8 filled with 1 & 0
[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]
concatenate a & b along row axis
[[0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0]]
Reshape without changing data
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
import numpy as np
a=np.full((8, 8), [0,1,0,1,0,1,0,1])
print("Create 4x8 filled with 0 & 1")
print("Before")
print(a)
#print(a[1::2,::2])
a[1::2,::2]=1
#print(a[1::2,1::2])
print("After")
a[1::2,1::2]=0
print(a)




Create 4x8 filled with 0 & 1
Before
[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]
After
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
import numpy as np
a=np.array([
  [0,9,8,7],
  [6,5,4,3],
  [2,1,0,9],
  [8,7,6,5]
])
print(a)
print(a[1::2,::2])
a[1::2,::2]=1
print(a)

[[0 9 8 7]
 [6 5 4 3]
 [2 1 0 9]
 [8 7 6 5]]
[[6 4]
 [8 6]]
[[0 9 8 7]
 [1 5 1 3]
 [2 1 0 9]
 [1 7 1 5]]
