<a href="https://colab.research.google.com/github/kjeyaram-orcl/DataScience/blob/main/NumpyArray_Manipulations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Iterating Numpy Array

In [12]:
import numpy as np
# iterate the arrays in each dimension
a = np.array([[9,7,3],[5,6,4]])
for x in a:
  for y in x:
    print(y)

9
7
3
5
6
4


In [13]:
import numpy as np
# iterate through all the rows
a = np.array([[9,7,3],[5,6,4]])
for x in a:
  print(x)

[9 7 3]
[5 6 4]


#Filtering Numpy Array

In [22]:
import numpy as np

#Filter Array using boolean index list

a = np.array([1, 2, 3, 4])
x = [False, True, False, True]
print(a[x])

[2 4]


In [23]:
import numpy as np

#Filter Array with condition

a = np.array([1, 2, 3, 4])
b=[]
for e in a:
  if e > 2:
    b.append(e)

print (b)

[3, 4]


In [24]:
import numpy as np

#Filter Array with condition and retrieve data using boolean index list

a = np.array([1, 2, 3, 4])
b=[];
for e in a:
  if e%2==0:
    b.append(True)
  else:
    b.append(False)
print(a[b])

[2 4]


#Sorting Numpy Array


```
# This is formatted as code
```



In [3]:
import numpy as np
#sort array with axis

a = np.array([[9,7,3],[5,6,4]])
print(np.sort(a,axis=None))          # flatten sort
print(np.sort(a,axis=-1))            # Row sort
print(np.sort(a,axis=0))             # column sort


[3 4 5 6 7 9]
[[3 7 9]
 [4 5 6]]
[[5 6 3]
 [9 7 4]]


In [2]:
import numpy as np
#sort array with key

dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.6, 42),('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)       # create a structured array
#print(a)
b=np.sort(a, order='height')  # sort by height
print(b)


[(b'Lancelot', 1.6, 42) (b'Galahad', 1.7, 38) (b'Arthur', 1.8, 41)]


#Searching elements in Numpy Array

In [6]:
import numpy as np

# return indexes where the values are even

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.where(a%2 == 0)
print(b)

(array([1, 3, 5, 7, 9]),)


In [7]:
import numpy as np

# return elements based on condition

a = np.arange(10)
b=np.where(a < 5, a, 10*a)
print(b)

[ 0  1  2  3  4 50 60 70 80 90]


In [8]:
import numpy as np

a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])
b=np.where(a < 4, a, -1)
print(b)

c=np.where(
        [
          [True, False],
          [True, True]
        ],
        [
          [1, 2],
          [3, 4]
        ],
        [
          [9, 8],
          [7, 6]
        ]
  )

print(c)

[[ 0  1  2]
 [ 0  2 -1]
 [ 0  3 -1]]
[[1 8]
 [3 4]]


In [9]:
import numpy as np

# return indexes where the value 7 should be inserted

a = np.array([6, 7, 8, 9])
b = np.searchsorted(a, 7)
print(b)

1


In [10]:
import numpy as np

# return indexes where the below values should be inserted

a= np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])
print(a)


[0 5 1 2]
