<a href="https://colab.research.google.com/github/kjeyaram-orcl/DataScience/blob/main/Numpy_ArraySlicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Slicing 1D Array

import numpy as np

a = np.array([0,9,8,7,6,5,4,3,2,1]) #Array 0 indexed

print(a[1:5])

[9 8 7 6]


In [ ]:
#Slicing 1D Array

import numpy as np

a = np.array([0,9,8,7,6,5,4,3,2,1]) #Array 0 indexed

print(a[:7])

[0 9 8 7 6 5 4]


In [ ]:
#Slicing 1D Array

import numpy as np

a = np.array([0,9,8,7,6,5,4,3,2,1]) #Array 0 indexed

print(a[-3:-1]) # Negative Indexing


In [ ]:
#Slicing 1D Array with Step

import numpy as np

a = np.array([0,9,8,7,6,5,4,3,2,1]) #Array 0 indexed

print(a[::2]) # Every other elements

[0 8 6 4 2]


In [ ]:
#Slicing 2D Array

import numpy as np

a = np.array(
    [
        [0,9,8,7,6],
        [5,4,3,2,1]
    ]
)

print(a[0:2, 1:4])

[[9 8 7]
 [4 3 2]]


In [ ]:
#Slicing 3D Array

import numpy as np

a = np.array(
  [
    [
        [0,9,8,7,6],
        [5,4,3,2,1]
    ],
    [
        [5,4,3,2,1],
        [0,9,8,7,6]
    ]
  ]

)

print(a[1,0,1:4])

[4 3 2]


In [10]:
import numpy as np

a = np.array([0,9,8,7,6])
x = a.copy()
a[0] = 1

print('Original', a)
print('Copy', x)


x = a.view()
x[0] = 1 # view does not own the data and any changes made to the view will affect the original array

print('Original', a)
print('View', x)

y=a.copy()
print('Copy returns', x.base)
print('View returns', y.base)



Original [1 9 8 7 6]
Copy [0 9 8 7 6]
Original [1 9 8 7 6]
View [1 9 8 7 6]
Copy returns [1 9 8 7 6]
View returns None
