<a href="https://colab.research.google.com/github/kjeyaram-orcl/DataScience/blob/main/Numpy_Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Statistics

In [5]:
import numpy as np

a = np.array([
    [10, 7, 4],
    [3, 2, 1]
    ])

print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=0,keepdims=True))
print(np.median(a, axis=1))


3.5
[6.5 4.5 2.5]
[[6.5 4.5 2.5]]
[7. 2.]


In [19]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print(np.std(a)) # flattened
print(np.std(a, axis=0)) #along rows
print(np.std(a, axis=1)) #along columns
print(np.std(a, where=[[False], [True]])) #Elements to include in the standard deviation


1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]
0.816496580927726
