<a href="https://colab.research.google.com/github/kjeyaram-orcl/DataScience/blob/main/NumpyArray_Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# convert 1D to 2D Array

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_a = a.reshape(4, 3)

print(new_a)
print("New Array Shape", new_a.shape)
print("Indexing new Array", new_a[3,1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
New Array Shape (4, 3)
Indexing new Array 11


In [ ]:
# convert 1D to 5D Array

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_a = a.reshape(1,1,2,2,3)

print(new_a)
print("New Array Shape", new_a.shape)
print("Indexing new Array", new_a[0,0,1,1,1])

[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]]]
New Array Shape (1, 1, 2, 2, 3)
Indexing new Array 11
