<a href="https://colab.research.google.com/github/kjeyaram-orcl/DataScience/blob/main/Numpy_LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Linear Algebra

In [ ]:
#Declaring a vector in Python using NumPy

import numpy as np
v = np.array([3, 2])
print(v)


[3 2]


In [ ]:
#Adding and Combining Vectors

from numpy import array

v = array([3, 2])
w = array([2, -1])

# sum the vectors
v_plus_w = v + w

# display summed vector
print(v_plus_w) # [5, 1]

[5 1]


In [ ]:
#Scaling Vectors
from numpy import array

v = array([3,1])

# scale the vector
scaled_v = 2.0 * v

# display scaled vector
print(scaled_v) # [6 2]

[6. 2.]


In [ ]:
#Scaled down by factor of .5

from numpy import array

v = array([3,1])

# scale the vector
scaled_v = 0.5 * v

# display scaled vector
print(scaled_v) # [6 2]



[1.5 0.5]


In [ ]:
#Linear Transformation, Transforming a vector using NumPy

from numpy import array

# Declare i-hat and j-hat
i_hat_x = array([2, 3])
j_hat_y = array([2, -1])

# compose basis matrix using i-hat and j-hat also need to transpose rows into columns
basis = array([i_hat_x, j_hat_y]).transpose()

# declare vector v 0
v = array([2,1])

# create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v) # [6, 5]

[6 5]


In [ ]:
#Combining two transformations

from numpy import array

# Transformation 1 (to rotate vector)
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformation 2 (to sheer vector)
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# Combine Transformations, apply sheer first and then rotation
combined = transform1 @ transform2

# Test
print("COMBINED MATRIX:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v)) # [-2, 3]

# we can also do it seperately
s=transform2.dot(v) # sheer
r=transform1.dot(s) # rotate
print("Sheer ", s) # [3, 2]
print("And then Rotate ", r) # [-2, 3]

COMBINED MATRIX:
 [[ 0 -1]
 [ 1  1]]
[-2  3]
Sheer  [3 2]
And then Rotate  [-2  3]


In [ ]:
# Applying the transformations in reverse ie., 1st rotate and then Sheer
from numpy import array

# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# Combine Transformations
combined = transform2 @ transform1

# Test
print("COMBINED MATRIX:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v))  # [-1, 1]


# we can also do it seperately
r=transform1.dot(v) # rotate
s=transform2.dot(r) # sheer
print("Rotate ", r) # [-2, 1]
print("And then Sheer ", s) # [-1, 1]



COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]
[-1  1]
Rotate  [-2  1]
And then Sheer  [-1  1]


In [ ]:
from numpy.linalg import det
from numpy import array

# 0 determinant means linear dependence
# 1 simple shear scaled determinant
# > 1 scaled
# Negative determinant - scaled and flipped

i_hat = array([-2, 1])
j_hat = array([3, -1.5])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant) # prints 0.0

In [ ]:
import numpy as np

#compute the determinant of 3x3

a = np.array([
    [6,1,1],
    [4,-2,5],
    [2,8,7]
    ])
result = np.linalg.det(a)
print(result)

-306.0


In [ ]:
# Inverse 2x2 Matrix
from sympy import *

A = Matrix([
    [4, 7],
    [2, 6]
])

X = A.inv()
print (X)

#Remember it must be true that: AA-1 = I

X = A.inv() * A
print (X) #Identity Matrix


Matrix([[3/5, -7/10], [-1/5, 2/5]])
Matrix([[1, 0], [0, 1]])


In [ ]:
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = Matrix([
    44,
    56,
    72
])

#AX=B -> X=B/A == X=B*A-1

X = A.inv() * B

print(X) #So x = 2, y = 34, and z = –8


Matrix([[2], [34], [-8]])


In [1]:
import numpy as np

#Eigenvector and Eigenvalue
#Av = λv -> Lambda(EigenValues), v(EigenVector), A (Matrix)


from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [-6, 3],
    [4, 5]
])

eigenvals, eigenvecs = eig(A)

print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)



EIGENVALUES
[-7.  6.]

EIGENVECTORS
[[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]
