<a href="https://colab.research.google.com/github/kjeyaram-orcl/DataScience/blob/main/Scipy/ScipyPractise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
from scipy import sparse as sp

x=np.array([
    [1,2,0,0,0,0,3],
    [0,0,4,0,0,5,0],
    [0,0,0,0,0,0,6]
           ])
s1 = sp.csr_matrix(x)

print(s1)

print (s1.data)

print (s1.indices)

#indptr[1] tells the number of non-zero data elements, upto end of first row.
#indptr[2] tells the number of non-zero data elements, starting from beggining upto end of second row...
print (s1.indptr)

# Convert the sparse matrix to a dense matrix - which has more number of zeros
X = s1.todense()

print(X)


  (0, 0)	1
  (0, 1)	2
  (0, 6)	3
  (1, 2)	4
  (1, 5)	5
  (2, 6)	6
[1 2 3 4 5 6]
[0 1 6 2 5 6]
[0 3 5 6]
[[1 2 0 0 0 0 3]
 [0 0 4 0 0 5 0]
 [0 0 0 0 0 0 6]]
